### ISSUE TITLE
IndexError in LowCloudFilter.filter_function

### ISSUE THREAD

**Issue by gerritholl** [m4sth0/fogpy#18]
When running the unit tests, `filters.LowCloudFilter.filter_function` gives an `IndexError`.  Apparently, this function assumes that `self.result_list` is at least as long as `self.index_list`:

https://github.com/gerritholl/fogpy/blob/f0129e1d5b89377c2f0bd755e6b257cd774e12c5/fogpy/filters.py#L959-L962

however, when debugging the unit test, I find that `len(self.index_list)=3793` whereas `len(self.result_list)=67`.

```
ERROR: test_fls_algorithm (fogpy.test.test_algorithms.Test_DayFogLowStratusAlgorithm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gholl/checkouts/fogpy/fogpy/test/test_algorithms.py", line 191, in test_fls_algorithm
    ret, mask = flsalgo.run()
  File "/home/gholl/checkouts/fogpy/fogpy/algorithms.py", line 98, in run
    self.procedure()
  File "/home/gholl/checkouts/fogpy/fogpy/algorithms.py", line 497, in procedure
    lowcloudfilter.apply()
  File "/home/gholl/checkouts/fogpy/fogpy/filters.py", line 131, in apply
    self.filter_function()
  File "/home/gholl/checkouts/fogpy/fogpy/filters.py", line 970, in filter_function
    self.cbh[r, c] = self.result_list[i][0]
IndexError: list index out of range
```

3793 corresponds to the number of tasks, I don't know why `self.result_list` only has 67 elements.  `self.result_list` is appended to by `self.log_result`:

https://github.com/gerritholl/fogpy/blob/f0129e1d5b89377c2f0bd755e6b257cd774e12c5/fogpy/filters.py#L1022-L1025

so it appears the algorithm assumes that every iteration has exactly one result, which appears to be not the case in the test run.

**Comment by gerritholl** [comment]
Could this be a consequence of https://github.com/gerritholl/fogpy/commit/460f432b676da618747acea36ba20a88a5dd2920?

https://github.com/gerritholl/fogpy/blob/f0129e1d5b89377c2f0bd755e6b257cd774e12c5/fogpy/filters.py#L1043

what happens when it's inside a thread and there is an uncaught exception?

There is an uncaught exception; when temporarily disabling threads such as in https://github.com/gerritholl/fogpy/commit/bd0eb2e9136acf83576e215b7dd9cc7b4df6d535, Python 3 fails at:

https://github.com/gerritholl/fogpy/blob/f0129e1d5b89377c2f0bd755e6b257cd774e12c5/fogpy/lowwatercloud.py#L282

which is valid in Python 2.  Thus this should be fixed with d9a8b427f8af155e28ccb3121b6f45607d67a03a.
