### ISSUE TITLE
Test_NightFogLowStratusAlgorithm.setUp uses unsupported geostationary TLE

### ISSUE THREAD

**Issue by gerritholl** [m4sth0/fogpy#19]
In the test routines, `Test_NightFogLowStratusAlgorithm.setUp` tries to set up a `pyorbital.Orbital` class with a geostationary TLE:

https://github.com/gerritholl/fogpy/blob/f0129e1d5b89377c2f0bd755e6b257cd774e12c5/fogpy/test/test_algorithms.py#L615-L622

However, `pyorbital.Orbital` does not support geostationary satellites, so this fails with a `NotImplementedError`:

```
Traceback (most recent call last):
  File "/home/gholl/checkouts/fogpy/fogpy/test/test_algorithms.py", line 622, in setUp 
    line2=self.tle.line2)
  File "/media/nas/x21324/miniconda3/envs/py37d/lib/python3.7/site-packages/pyorbital/orbital.py", line 167, in __init__
    self._sgdp4 = _SGDP4(self.orbit_elements)
  File "/media/nas/x21324/miniconda3/envs/py37d/lib/python3.7/site-packages/pyorbital/orbital.py", line 706, in __init__
    raise NotImplementedError('Deep space calculations not supported')
NotImplementedError: Deep space calculations not supported
```

This appears to have been the case for many years so I don't see how this test can have ever worked.

**Comment by gerritholl** [comment]
Apparently there were some local / home-grown changes to pyorbital for geostationary satellite zenith angle calculations, but it is not clear if this code was retained anywhere.
